### ISSUE TITLE
Add «Der Bund»-Blogs (Media)

### ISSUE THREAD

**Issue by chzellweger** [WPSwitzerland/wordpress-websites-switzerland-worldwide#10]
http://kulturstattbern.derbund.ch
http://zumrundenleder.derbund.ch
run on Wordpress. Basically all Tamedia-Blogs (maintained by MVA Internet Services)

**Comment by chzellweger** [comment]
...but on the other hand they are not "websites"...

**Comment by markhowellsmead** [comment]
Is there a collated list of them all anywhere? Any website (or microsite) can be added. But not every single blog in the world ;) These should be references for reference by people working with clients, as examples of what's possible.

**Comment by chzellweger** [comment]
that would be: http://www.derbund.ch/blogs/
but I see, I was maybe to quick here, sorry ;-)

**Comment by markhowellsmead** [comment]
Are all of them always made with WordPress?

**Comment by chzellweger** [comment]
afaik: yes!
