### ISSUE TITLE
Idea: Add a list of plugins built in Switzerland

### ISSUE THREAD

**Issue by neverything** [WPSwitzerland/wordpress-websites-switzerland-worldwide#35]
As suggested by members of the Zurich meetup group during the last meetup, they would be interested in having a list of WordPress plugins built in Switzerland or for Switzerland in this repo. I like the idea, what do you fine folks think?

**Comment by stefanbommeli** [comment]
I'd love to see that!

**Comment by markhowellsmead** [comment]
Fine by me. I'd suggest that only plugins from the official repository be included. This will encourage people to submit their work to the community.

**Comment by neverything** [comment]
@markhowellsmead absolutely, while as a dev I'd love to have all the plugins, it was requested by a user and therefore I totally agree with you to only include plugins that are on w.org. I'll prepare such a list and submit it via PR.

**Comment by acki** [comment]
Any news on this @neverything ?

**Comment by neverything** [comment]
@acki wow that's a long turn-over for a reply. Not yet, but please start listing the ones you have in the w.org repo.

https://profiles.wordpress.org/wearerequired#content-plugins
https://profiles.wordpress.org/swissspidy#content-plugins
https://profiles.wordpress.org/grapplerulrich#content-plugins
https://profiles.wordpress.org/keycdn#content-plugins
https://profiles.wordpress.org/liip#content-plugins
https://profiles.wordpress.org/cubetech#content-plugins

And so on, will get in touch with @markhowellsmead and @nico-martin soon regarding the wpswitzerland.ch website.

**Comment by markhowellsmead** [comment]
Closed as no further action.
